### PR TITLE
improve incoming robot tutorial's readability

### PR DESCRIPTION
**Pull request by bcho**
- fix json & markdown syntax
- fix minor typo
- use `{{webhookUrl}}` template var to enable coping & pasting commands

### CODE REVIEW

**Comment by bcho** [comment]
_2015-12-25_11 3a42

**Comment by bcho** [comment]
@loddit @xtang

**Comment by loddit** [comment]
LGTM

**Comment by yuanbohan** [comment]
LGTM

**Comment by xtang** [comment]
LGTM

**Pull request merged**
